# Generated by Django 5.0.6 on 2024-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('information', models.TextField()),
                ('plot', models.TextField()),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('available_platforms', models.CharField(max_length=200)),
                ('actors', models.ManyToManyField(related_name='series', to='series.actor')),
            ],
        ),
    ]
