# Generated by Django 5.0.6 on 2024-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform_icon',
            field=models.ImageField(default=42, upload_to='icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='platform_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
