# Generated by Django 5.0.6 on 2024-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_platform_icon_movie_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='platform_icon',
            field=models.ImageField(default='allinall/static/images/Bad Boys Poster.jpeg', upload_to='icons/'),
        ),
    ]
